/**
 * Field paths.
 *
 * Signals address extracted data with paths like `tiers[].name` or `jobs[]`.
 * `[]` means "iterate this collection".
 *
 * The wrinkle this module exists to absorb: we do not control the shape of the
 * data. A collector is generated by AI from the `watch` description, so a
 * pricing page may come back either as
 *
 *   [{ tiers: [{ name: 'Pro' }, { name: 'Enterprise' }] }]     (one document row)
 *   [{ name: 'Pro' }, { name: 'Enterprise' }]                   (one row per tier)
 *
 * Both are correct readings of the same instruction. Rather than pin the
 * collector to one shape — which would make every heal a schema migration —
 * paths resolve against either. `tiers[].name` finds the named collection if it
 * exists, and otherwise falls back to treating the rows themselves as that
 * collection. This is what lets a healed collector keep working when Bright
 * Data's AI re-derives the extraction slightly differently.
 */

export interface PathSegment {
  key: string
  iterate: boolean
}

export function parsePath(path: string): PathSegment[] {
  return path
    .split('.')
    .filter(Boolean)
    .map((raw) => {
      const iterate = raw.endsWith('[]')
      return { key: iterate ? raw.slice(0, -2) : raw, iterate }
    })
}

const isRecord = (v: unknown): v is Record<string, unknown> =>
  typeof v === 'object' && v !== null && !Array.isArray(v)

/**
 * Resolve a path to a flat list of leaf values.
 * Missing keys yield nothing; explicit nulls are preserved, because the
 * difference between "absent" and "null" is what drift detection measures.
 */
export function resolveField(rows: unknown[], path: string): unknown[] {
  const segments = parsePath(path)
  if (segments.length === 0) return rows

  const [head, ...tail] = segments as [PathSegment, ...PathSegment[]]

  // Does the named collection exist on the rows?
  const named: unknown[] = []
  let foundNamed = false
  for (const row of rows) {
    if (isRecord(row) && head.key in row) {
      foundNamed = true
      const v = row[head.key]
      if (head.iterate && Array.isArray(v)) named.push(...v)
      else named.push(v)
    }
  }

  // Fallback: the rows ARE the collection the path names.
  const current = foundNamed ? named : rows

  let values: unknown[] = current
  for (const seg of tail) {
    const next: unknown[] = []
    for (const v of values) {
      if (!isRecord(v)) continue
      if (!(seg.key in v)) continue
      const child = v[seg.key]
      if (seg.iterate && Array.isArray(child)) next.push(...child)
      else next.push(child)
    }
    values = next
  }
  return values
}

/** Resolve to string values, dropping absent entries but keeping empty strings. */
export function resolveStrings(rows: unknown[], path: string): string[] {
  return resolveField(rows, path)
    .filter((v) => v !== undefined && v !== null)
    .map((v) => (typeof v === 'string' ? v : JSON.stringify(v)))
}

/**
 * How many items a collection path addresses.
 * `jobs[]` counts the jobs; a leaf path counts resolved values.
 */
export function resolveCount(rows: unknown[], path: string): number {
  return resolveField(rows, path).length
}

/**
 * Fraction of resolved values that are null, undefined, or empty string.
 * Returns 1 when the path resolves to nothing at all — a field that vanished is
 * maximally broken, which is exactly what Anneal needs to notice.
 */
export function nullRate(rows: unknown[], path: string): number {
  const values = resolveField(rows, path)
  if (values.length === 0) return 1
  const empty = values.filter(
    (v) => v === null || v === undefined || (typeof v === 'string' && v.trim() === ''),
  ).length
  return empty / values.length
}

/** True when the path resolves to no values whatsoever. */
export const isMissing = (rows: unknown[], path: string): boolean =>
  resolveField(rows, path).length === 0
